language: node_js
node_js:
  - "8.12.0"
cache:
  directories:
  - node_modules
install:
  - npm install
jobs:
  include:
    - stage: test
      script:
      - npm test
      - npm run coverage
    - stage: deploy-prod
      script:
      - npm deploy.prod
stages:
  - test
  - name: deploy-prod
    if: branch =~ /prod-.*/

