language: node_js
node_js:
  - "8.12.0"
cache:
  directories:
  - node_modules
install:
  - npm install
  - npm install ask-cli -g
jobs:
  include:
    - stage: test
      script:
      - npm test
      - npm run coverage
    - stage: deploy-dev
      script:
      - npm run deploy.dev
    - stage: deploy-prod
      script:
      - npm run deploy.prod
stages:
  - test
  - name: deploy-dev
    if: branch =~ /dev-.*/
  - name: deploy-prod
    if: branch =~ /prod-.*/
  
