language: node_js
node_js:
  - "10.16.3"
cache:
  directories:
  - node_modules
install:
  - npm install
  - npm install ask-cli -g
jobs:
  include:
    - stage: test
      script:
      - npm test
      - npm run coverage
    - stage: deploy-dev
      script:
      - npm run deploy-dev
      - export findReplace.INVOCATION_NAME="must classic movies"
      - npm run test-e2e
    - stage: deploy-prod
      script:
      - npm run deploy-prod
      - npm run test-e2e
stages:
  - test
  - name: deploy-dev
    if: branch =~ /dev-.*/
  - name: deploy-prod
    if: branch =~ /prod-.*/
  
