module.exports = {
    ATTR_COUNTER: "COUNTER",
    ATTR_PREVIOUS_QUESTIONS: "PREVIOUS_QUESTIONS",
    ATTR_QUESTION_INDEX: "QUESTION_INDEX",
    ATTR_SCORE: "SCORE",
    ATTR_STATE: "STATE",

    SPEECHCONS_CORRECT: ["Booya", 
        "All righty", 
        "Bam", 
        "Bazinga", 
        "Bingo", 
        "Boom", 
        "Bravo", 
        "Cha Ching", 
        "Cheers", 
        "Dynomite", 
        "Hip hip hooray", 
        "Hurrah", 
        "Hurray", 
        "Huzzah", 
        "Oh dear.  Just kidding.  Hurray", 
        "Kaboom", 
        "Kaching", 
        "Oh snap", 
        "Phew",
        "Righto", 
        "Way to go", 
        "Well done", 
        "Whee", 
        "Woo hoo", 
        "Yay", 
        "Wowza", 
        "Yowsa"],
    SPEECHCONS_WRONG: ["Argh", 
        "Aw man", 
        "Blarg", 
        "Blast", 
        "Boo", 
        "Bummer", 
        "Darn", 
        "D'oh", 
        "Dun dun dun", 
        "Eek", 
        "Honk", 
        "Le sigh", 
        "Mamma mia", 
        "Oh boy", 
        "Oh dear", 
        "Oof", 
        "Ouch", 
        "Ruh roh", 
        "Shucks", 
        "Uh oh", 
        "Wah wah", 
        "Whoops a daisy", 
        "Yikes"],

    SPEECH_ANOTHER_QUESTION: "Do you want to answer another question?",
    SPEECH_EXIT_SKILL: "Thank you for playing the Classic Movie Musts Quiz Game!  Keep up with your classics!",
    SPEECH_HELP: "Say play trivia, play latest, or play with a movie name - such as play rear window",
    SPEECH_NO_MORE_QUESTIONS: "That's all the questions we have. We will add more, so come back soon - in the meantime, keep up with your classics",
    SPEECH_START_QUIZ: "Great - here is your first question.",
    SPEECH_WELCOME: "Welcome to Classic Movie Musts!  " +
      "You can play trivia, listen to the latest podcast, or ask for a podcast by name.  " + 
      "What would you like to do?",

    STATE_ANSWERING: "ANSWERING",
    STATE_LAUNCHED: "LAUNCHED",
    STATE_MORE: "ANOTHER_QUESTION",
};
